/** Profile page templates — Tailwind class presets */
export const TEMPLATES = [
  {
    id: "purple-pink",
    name: "Purple Pulse",
    description: "Classic gradient — matches the default brand look",
    preview: "from-purple-600 to-pink-600",
    page: "bg-gradient-to-br from-purple-900 via-purple-800 to-pink-600",
    card: "bg-white border-purple-100",
    cardTitle: "text-gray-800",
    cardSub: "text-purple-600",
    bio: "text-gray-600",
    avatarBorder: "border-purple-200",
    button: "bg-gradient-to-r from-purple-600 to-pink-600 text-white hover:scale-[1.02] hover:shadow-xl",
    reviewsAccent: "text-purple-700",
  },
  {
    id: "ocean",
    name: "Ocean Blue",
    description: "Cool blues for creators and devs",
    preview: "from-cyan-500 to-blue-700",
    page: "bg-gradient-to-br from-slate-900 via-blue-900 to-cyan-800",
    card: "bg-white/95 border-cyan-100",
    cardTitle: "text-slate-900",
    cardSub: "text-cyan-700",
    bio: "text-slate-600",
    avatarBorder: "border-cyan-300",
    button: "bg-gradient-to-r from-cyan-500 to-blue-600 text-white hover:scale-[1.02] hover:shadow-xl",
    reviewsAccent: "text-cyan-700",
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Warm orange and coral tones",
    preview: "from-orange-500 to-rose-600",
    page: "bg-gradient-to-br from-orange-900 via-rose-800 to-amber-700",
    card: "bg-white border-orange-100",
    cardTitle: "text-gray-900",
    cardSub: "text-orange-600",
    bio: "text-gray-600",
    avatarBorder: "border-orange-200",
    button: "bg-gradient-to-r from-orange-500 to-rose-600 text-white hover:scale-[1.02] hover:shadow-xl",
    reviewsAccent: "text-orange-700",
  },
  {
    id: "forest",
    name: "Forest",
    description: "Natural greens and earth tones",
    preview: "from-emerald-600 to-green-800",
    page: "bg-gradient-to-br from-emerald-950 via-green-900 to-teal-800",
    card: "bg-white border-emerald-100",
    cardTitle: "text-gray-900",
    cardSub: "text-emerald-700",
    bio: "text-gray-600",
    avatarBorder: "border-emerald-200",
    button: "bg-gradient-to-r from-emerald-600 to-green-700 text-white hover:scale-[1.02] hover:shadow-xl",
    reviewsAccent: "text-emerald-700",
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Dark mode with violet accents",
    preview: "from-violet-600 to-indigo-900",
    page: "bg-gradient-to-br from-gray-950 via-indigo-950 to-violet-950",
    card: "bg-gray-900 border-violet-800 text-white",
    cardTitle: "text-white",
    cardSub: "text-violet-300",
    bio: "text-gray-300",
    avatarBorder: "border-violet-500",
    button: "bg-gradient-to-r from-violet-600 to-indigo-700 text-white hover:scale-[1.02] hover:shadow-xl",
    reviewsAccent: "text-violet-400",
  },
  {
    id: "neon",
    name: "Neon Nights",
    description: "Bold cyberpunk pink and purple",
    preview: "from-fuchsia-500 to-purple-900",
    page: "bg-gradient-to-br from-black via-purple-950 to-fuchsia-950",
    card: "bg-gray-900/90 border-fuchsia-500/30 text-white",
    cardTitle: "text-white",
    cardSub: "text-fuchsia-400",
    bio: "text-gray-300",
    avatarBorder: "border-fuchsia-400",
    button: "bg-gradient-to-r from-fuchsia-500 to-purple-600 text-white shadow-lg shadow-fuchsia-500/30 hover:scale-[1.02]",
    reviewsAccent: "text-fuchsia-400",
  },
  {
    id: "minimal",
    name: "Minimal Light",
    description: "Clean white and soft gray",
    preview: "from-gray-100 to-gray-300",
    page: "bg-gradient-to-br from-gray-50 via-white to-gray-100",
    card: "bg-white border-gray-200 shadow-md",
    cardTitle: "text-gray-900",
    cardSub: "text-gray-500",
    bio: "text-gray-600",
    avatarBorder: "border-gray-300",
    button: "bg-gray-900 text-white hover:bg-gray-800 hover:scale-[1.02]",
    reviewsAccent: "text-gray-700",
  },
  {
    id: "gold",
    name: "Gold Luxury",
    description: "Premium black and gold",
    preview: "from-amber-400 to-yellow-700",
    page: "bg-gradient-to-br from-zinc-950 via-neutral-900 to-amber-950",
    card: "bg-zinc-900 border-amber-600/40 text-white",
    cardTitle: "text-amber-50",
    cardSub: "text-amber-400",
    bio: "text-zinc-300",
    avatarBorder: "border-amber-500",
    button: "bg-gradient-to-r from-amber-500 to-yellow-600 text-black font-bold hover:scale-[1.02] hover:shadow-xl",
    reviewsAccent: "text-amber-400",
  },
  {
    id: "candy",
    name: "Candy Pop",
    description: "Playful pastel gradients",
    preview: "from-pink-400 to-sky-400",
    page: "bg-gradient-to-br from-pink-200 via-purple-100 to-sky-200",
    card: "bg-white border-pink-200",
    cardTitle: "text-gray-800",
    cardSub: "text-pink-600",
    bio: "text-gray-600",
    avatarBorder: "border-pink-300",
    button: "bg-gradient-to-r from-pink-400 to-sky-400 text-white hover:scale-[1.02] hover:shadow-lg",
    reviewsAccent: "text-pink-600",
  },
  {
    id: "slate",
    name: "Slate Pro",
    description: "Professional blue-gray",
    preview: "from-slate-600 to-slate-800",
    page: "bg-gradient-to-br from-slate-800 via-slate-700 to-slate-900",
    card: "bg-slate-50 border-slate-200",
    cardTitle: "text-slate-900",
    cardSub: "text-slate-600",
    bio: "text-slate-600",
    avatarBorder: "border-slate-400",
    button: "bg-slate-700 text-white hover:bg-slate-600 hover:scale-[1.02]",
    reviewsAccent: "text-slate-700",
  },
];

export const DEFAULT_TEMPLATE_ID = "purple-pink";

export function getTemplateById(id) {
  return TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];
}

export function isValidTemplateId(id) {
  return TEMPLATES.some((t) => t.id === id);
}
